# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# fabric-loom 1.17 \u8981\u6C42 JVM 21+ \u8FD0\u884C\u6784\u5EFA\uFF1B\u7F16\u8BD1\u4EA7\u7269\u4ECD\u4E3A release=21
# \u672C\u673A\u8DEF\u5F84\uFF0C\u79FB\u690D\u5230\u5176\u4ED6\u73AF\u5883\u65F6\u9700\u8C03\u6574
org.gradle.java.home=C:/Software/jdk-21

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
# \u6CE8\u610F\uFF1A1.21.11 \u7684 fabric-api \u5168\u90E8\u8981\u6C42 fabricloader >= 0.17.3\uFF081.21.1 \u65F6\u4EE3\u7684 0.16.13 \u65E0\u6CD5\u52A0\u8F7D\uFF09
# \u4E3A\u517C\u5BB9\u66F4\u591A 1.21.11 \u6574\u5408\u5305\uFF0C\u91C7\u7528\u6700\u65E9\u53EF\u8FD0\u884C\u7248\u672C\uFF1Aloader 0.17.3\uFF08\u6EE1\u8DB3 >=0.17.3 \u7684\u6700\u4F4E\u7248\uFF09\u3001
# fabric-api 0.139.1\uFF080.139.0 \u53CA\u66F4\u65E9\u4E0E\u6700\u7EC8\u7248 1.21.11 \u7684 GameRules/\u6CE8\u518C\u8868 mixin \u4E0D\u517C\u5BB9\uFF0C\u542F\u52A8\u5D29\u6E83\uFF09
minecraft_version=1.21.11
loader_version=0.17.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.0.3
group=cn.sd.jrz

# Dependencies
fabric_api_version=0.139.4+1.21.11