org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.41-beta
mod_id=autoresource
mod_name=Auto Resource
mod_license=GNU LGPL v3
mod_version=0.1.8
mod_group_id=cn.sd.jrz