modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://gitee.com/scrambled_egg_with_eek/auto-resource/issues"
license="GNU LGPL v3"
[[mods]]
    modId="autoresource"
    version="0.1.5"
    displayName="Auto Resource"
    logoFile="modIcon.png"
    credits="Thanks for All"
    updateJSONURL="https://gitee.com/scrambled_egg_with_eek/auto-resource/raw/master/update.json"
    displayURL="https://gitee.com/scrambled_egg_with_eek/auto-resource"
    authors="JRZ"
    description='''
    Water, Lava, Stone, Forge Energy and more.
    '''
[[dependencies.autoresource]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.autoresource]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"