modLoader = "javafml"
license = "${mod_license}"
issueTrackerURL="https://gitee.com/scrambled_egg_with_eek/auto-resource/issues"
[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    updateJSONURL="https://gitee.com/scrambled_egg_with_eek/auto-resource/raw/master/update.json"
    displayURL="https://gitee.com/scrambled_egg_with_eek/auto-resource"
    logoFile="modIcon.png"
    authors = "JRZ"
    description = '''Water, Lava, Stone, Forge Energy and more.'''
[[dependencies.${ mod_id }]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${ mod_id }]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"